// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGqu0qvHyOvL8_Sb0xNvGGpLvMRF9ZKI0',
    appId: '1:624854650161:android:8191ebb7da9910f7117410',
    messagingSenderId: '624854650161',
    projectId: 'srekn-fintra',
    databaseURL: 'https://srekn-fintra-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'srekn-fintra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfUeV6Nh34GzZJ6PVWnyu1zP8vWczX8i4',
    appId: '1:624854650161:ios:f2a8c0830e71b34f117410',
    messagingSenderId: '624854650161',
    projectId: 'srekn-fintra',
    databaseURL: 'https://srekn-fintra-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'srekn-fintra.firebasestorage.app',
    iosBundleId: 'com.example.sreknFintra',
  );
}
